-- =====================================================================
-- GLOBAL SOLUTION 2026 - FIAP - Economia Espacial
-- Disciplina: DATABASE DESIGN
-- Grupo: Stratfy (Turma 2ESPH - Engenharia de Software)
--   Anthony Sforzin       - RM562096
--   Luigi Mendes Cabrini  - RM563552
--   Rogerio Cruz Arroyo   - RM563517
--   Bruno Koeke           - RM561309
--
-- Tema: SISTEMA DE DETECCAO DE INCENDIOS FLORESTAIS
--       (focos de calor por satelite + clima + desmatamento, Brasil 2025)
--
-- Arquivo: DDL Oracle COMPLETO do modelo relacional (10 tabelas)
--          SEQUENCEs, CREATE TABLE, PK, FK, UNIQUE, CHECK, indices,
--          COMMENT ON e INSERTs de exemplo com DADOS REAIS.
--
-- SGBD-alvo: Oracle Database 19c/21c/23ai.
-- Observacao: os INSERTs de carga completa (dados reais em volume) sao
--             gerados pelo ETL em sql/insercoes_dados_reais.sql.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0) LIMPEZA (ordem reversa de dependencia). Ignore erros na 1a execucao.
-- ---------------------------------------------------------------------
-- Em Oracle, use o bloco abaixo apenas se as tabelas ja existirem.
-- DROP TABLE T_FOCO_CONDICAO_CLIM     CASCADE CONSTRAINTS;
-- DROP TABLE T_DESMATAMENTO_BIOMA     CASCADE CONSTRAINTS;
-- DROP TABLE T_MEDICAO_CLIMATICA      CASCADE CONSTRAINTS;
-- DROP TABLE T_LOCALIZACAO_ESTACAO    CASCADE CONSTRAINTS;
-- DROP TABLE T_ESTACAO_METEOROLOGICA  CASCADE CONSTRAINTS;
-- DROP TABLE T_FOCO_CALOR             CASCADE CONSTRAINTS;
-- DROP TABLE T_SATELITE               CASCADE CONSTRAINTS;
-- DROP TABLE T_MUNICIPIO              CASCADE CONSTRAINTS;
-- DROP TABLE T_ESTADO                 CASCADE CONSTRAINTS;
-- DROP TABLE T_BIOMA                  CASCADE CONSTRAINTS;
-- DROP SEQUENCE SEQ_BIOMA;
-- DROP SEQUENCE SEQ_ESTADO;
-- DROP SEQUENCE SEQ_MUNICIPIO;
-- DROP SEQUENCE SEQ_SATELITE;
-- DROP SEQUENCE SEQ_FOCO;
-- DROP SEQUENCE SEQ_ESTACAO;
-- DROP SEQUENCE SEQ_MEDICAO;
-- DROP SEQUENCE SEQ_DESMAT;

-- ---------------------------------------------------------------------
-- 1) SEQUENCES (geracao de chaves substitutas / surrogate keys)
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_BIOMA      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ESTADO     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MUNICIPIO  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SATELITE   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOCO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ESTACAO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDICAO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DESMAT     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ---------------------------------------------------------------------
-- 2) TABELAS DE DOMINIO / DIMENSAO
-- ---------------------------------------------------------------------

-- 2.1) T_BIOMA --------------------------------------------------------
CREATE TABLE T_BIOMA (
    ID_BIOMA   NUMBER(4)      NOT NULL,
    NM_BIOMA   VARCHAR2(40)   NOT NULL,
    CONSTRAINT PK_BIOMA       PRIMARY KEY (ID_BIOMA),
    CONSTRAINT UK_BIOMA_NOME  UNIQUE (NM_BIOMA)
);

COMMENT ON TABLE  T_BIOMA            IS 'Biomas brasileiros monitorados (classificacao IBGE/MapBiomas).';
COMMENT ON COLUMN T_BIOMA.ID_BIOMA   IS 'Identificador substituto do bioma (PK).';
COMMENT ON COLUMN T_BIOMA.NM_BIOMA   IS 'Nome do bioma: Amazonia, Cerrado, Caatinga, Mata Atlantica, Pantanal, Pampa.';

-- 2.2) T_ESTADO -------------------------------------------------------
CREATE TABLE T_ESTADO (
    ID_ESTADO   NUMBER(4)     NOT NULL,
    NM_ESTADO   VARCHAR2(60)  NOT NULL,
    SG_UF       CHAR(2)       NOT NULL,
    NM_REGIAO   VARCHAR2(15)  NOT NULL,
    CONSTRAINT PK_ESTADO       PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UK_ESTADO_UF    UNIQUE (SG_UF),
    CONSTRAINT CK_ESTADO_REGIAO CHECK
        (NM_REGIAO IN ('Norte','Nordeste','Centro-Oeste','Sudeste','Sul'))
);

COMMENT ON TABLE  T_ESTADO            IS 'Unidades da Federacao (27 UFs), codigos IBGE.';
COMMENT ON COLUMN T_ESTADO.ID_ESTADO  IS 'Codigo IBGE da UF (PK). Ex.: 35 = Sao Paulo.';
COMMENT ON COLUMN T_ESTADO.NM_ESTADO  IS 'Nome da Unidade da Federacao.';
COMMENT ON COLUMN T_ESTADO.SG_UF      IS 'Sigla da UF (2 letras). Unica.';
COMMENT ON COLUMN T_ESTADO.NM_REGIAO  IS 'Regiao geografica (Norte/Nordeste/Centro-Oeste/Sudeste/Sul).';

-- 2.3) T_MUNICIPIO ----------------------------------------------------
CREATE TABLE T_MUNICIPIO (
    ID_MUNICIPIO    NUMBER(8)      NOT NULL,
    NM_MUNICIPIO    VARCHAR2(120)  NOT NULL,
    ID_ESTADO       NUMBER(4)      NOT NULL,
    CD_MICRORREGIAO NUMBER(6),
    LATITUDE        NUMBER(9,6),
    LONGITUDE       NUMBER(9,6),
    CONSTRAINT PK_MUNICIPIO       PRIMARY KEY (ID_MUNICIPIO),
    CONSTRAINT FK_MUNICIPIO_ESTADO FOREIGN KEY (ID_ESTADO)
        REFERENCES T_ESTADO (ID_ESTADO),
    CONSTRAINT UK_MUNICIPIO_NOME_UF UNIQUE (NM_MUNICIPIO, ID_ESTADO),
    CONSTRAINT CK_MUNICIPIO_LAT   CHECK (LATITUDE  BETWEEN -90  AND 90),
    CONSTRAINT CK_MUNICIPIO_LON   CHECK (LONGITUDE BETWEEN -180 AND 180)
);

COMMENT ON TABLE  T_MUNICIPIO                 IS 'Municipios brasileiros (codigo IBGE 7 digitos) com centroide.';
COMMENT ON COLUMN T_MUNICIPIO.ID_MUNICIPIO    IS 'Codigo IBGE do municipio (7 digitos) - PK.';
COMMENT ON COLUMN T_MUNICIPIO.NM_MUNICIPIO    IS 'Nome do municipio.';
COMMENT ON COLUMN T_MUNICIPIO.ID_ESTADO       IS 'FK para T_ESTADO (UF do municipio).';
COMMENT ON COLUMN T_MUNICIPIO.CD_MICRORREGIAO IS 'Codigo IBGE da microrregiao.';
COMMENT ON COLUMN T_MUNICIPIO.LATITUDE        IS 'Latitude do centroide do municipio (graus decimais).';
COMMENT ON COLUMN T_MUNICIPIO.LONGITUDE       IS 'Longitude do centroide do municipio (graus decimais).';

-- 2.4) T_SATELITE -----------------------------------------------------
CREATE TABLE T_SATELITE (
    ID_SATELITE    NUMBER(4)     NOT NULL,
    NM_SATELITE    VARCHAR2(40)  NOT NULL,
    FL_REFERENCIA  CHAR(1)       DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_SATELITE        PRIMARY KEY (ID_SATELITE),
    CONSTRAINT UK_SATELITE_NOME   UNIQUE (NM_SATELITE),
    CONSTRAINT CK_SATELITE_REF    CHECK (FL_REFERENCIA IN ('S','N'))
);

COMMENT ON TABLE  T_SATELITE               IS 'Satelites de monitoramento de focos de calor do programa BDQueimadas/INPE.';
COMMENT ON COLUMN T_SATELITE.ID_SATELITE   IS 'Identificador substituto do satelite (PK).';
COMMENT ON COLUMN T_SATELITE.NM_SATELITE   IS 'Nome do satelite/sensor. Ex.: AQUA_M-T, NOAA-20, GOES-19.';
COMMENT ON COLUMN T_SATELITE.FL_REFERENCIA IS 'Flag S/N: satelite de referencia do INPE para comparacao historica (AQUA_M-T = S).';

-- ---------------------------------------------------------------------
-- 3) TABELA FATO PRINCIPAL: FOCOS DE CALOR
-- ---------------------------------------------------------------------

-- 3.1) T_FOCO_CALOR ---------------------------------------------------
CREATE TABLE T_FOCO_CALOR (
    ID_FOCO            NUMBER(12)    NOT NULL,
    FOCO_ID_BDQ        VARCHAR2(40),
    ID_SATELITE        NUMBER(4)     NOT NULL,
    ID_MUNICIPIO       NUMBER(8),
    ID_BIOMA           NUMBER(4),
    DT_PASSAGEM        TIMESTAMP     NOT NULL,
    LATITUDE           NUMBER(9,6)   NOT NULL,
    LONGITUDE          NUMBER(9,6)   NOT NULL,
    NUM_DIAS_SEM_CHUVA NUMBER(4),
    PRECIPITACAO_MM    NUMBER(7,2),
    RISCO_FOGO         NUMBER(4,3),
    FRP_MW             NUMBER(9,2),
    CONSTRAINT PK_FOCO_CALOR        PRIMARY KEY (ID_FOCO),
    CONSTRAINT FK_FOCO_SATELITE     FOREIGN KEY (ID_SATELITE)
        REFERENCES T_SATELITE (ID_SATELITE),
    CONSTRAINT FK_FOCO_MUNICIPIO    FOREIGN KEY (ID_MUNICIPIO)
        REFERENCES T_MUNICIPIO (ID_MUNICIPIO),
    CONSTRAINT FK_FOCO_BIOMA        FOREIGN KEY (ID_BIOMA)
        REFERENCES T_BIOMA (ID_BIOMA),
    CONSTRAINT CK_FOCO_LAT          CHECK (LATITUDE  BETWEEN -90  AND 90),
    CONSTRAINT CK_FOCO_LON          CHECK (LONGITUDE BETWEEN -180 AND 180),
    CONSTRAINT CK_FOCO_RISCO        CHECK (RISCO_FOGO BETWEEN 0 AND 1),
    CONSTRAINT CK_FOCO_DIAS         CHECK (NUM_DIAS_SEM_CHUVA >= 0),
    CONSTRAINT CK_FOCO_PRECIP       CHECK (PRECIPITACAO_MM >= 0),
    CONSTRAINT CK_FOCO_FRP          CHECK (FRP_MW >= 0)
);

COMMENT ON TABLE  T_FOCO_CALOR                    IS 'Tabela fato: focos de calor detectados por satelite (BDQueimadas/INPE, 2025).';
COMMENT ON COLUMN T_FOCO_CALOR.ID_FOCO            IS 'Identificador substituto do foco (PK).';
COMMENT ON COLUMN T_FOCO_CALOR.FOCO_ID_BDQ        IS 'Identificador de origem no BDQueimadas (quando disponivel).';
COMMENT ON COLUMN T_FOCO_CALOR.ID_SATELITE        IS 'FK para T_SATELITE: satelite que detectou o foco.';
COMMENT ON COLUMN T_FOCO_CALOR.ID_MUNICIPIO       IS 'FK para T_MUNICIPIO: municipio do foco (pode ser nulo se nao casado com IBGE).';
COMMENT ON COLUMN T_FOCO_CALOR.ID_BIOMA           IS 'FK para T_BIOMA: bioma do foco.';
COMMENT ON COLUMN T_FOCO_CALOR.DT_PASSAGEM        IS 'Data/hora UTC da passagem do satelite que registrou o foco.';
COMMENT ON COLUMN T_FOCO_CALOR.LATITUDE           IS 'Latitude do foco (graus decimais).';
COMMENT ON COLUMN T_FOCO_CALOR.LONGITUDE          IS 'Longitude do foco (graus decimais).';
COMMENT ON COLUMN T_FOCO_CALOR.NUM_DIAS_SEM_CHUVA IS 'Numero de dias sem chuva no local ate a data do foco.';
COMMENT ON COLUMN T_FOCO_CALOR.PRECIPITACAO_MM    IS 'Precipitacao acumulada (mm) associada ao foco.';
COMMENT ON COLUMN T_FOCO_CALOR.RISCO_FOGO         IS 'Indice de risco de fogo calculado pelo INPE [0..1].';
COMMENT ON COLUMN T_FOCO_CALOR.FRP_MW             IS 'Fire Radiative Power (potencia radiativa do fogo) em megawatts.';

-- ---------------------------------------------------------------------
-- 4) SUBSISTEMA METEOROLOGICO (INMET)
-- ---------------------------------------------------------------------

-- 4.1) T_ESTACAO_METEOROLOGICA ----------------------------------------
CREATE TABLE T_ESTACAO_METEOROLOGICA (
    ID_ESTACAO    NUMBER(6)      NOT NULL,
    CD_WMO        VARCHAR2(10)   NOT NULL,
    NM_ESTACAO    VARCHAR2(120)  NOT NULL,
    ID_ESTADO     NUMBER(4)      NOT NULL,
    DT_FUNDACAO   DATE,
    CONSTRAINT PK_ESTACAO          PRIMARY KEY (ID_ESTACAO),
    CONSTRAINT FK_ESTACAO_ESTADO   FOREIGN KEY (ID_ESTADO)
        REFERENCES T_ESTADO (ID_ESTADO),
    CONSTRAINT UK_ESTACAO_WMO      UNIQUE (CD_WMO)
);

COMMENT ON TABLE  T_ESTACAO_METEOROLOGICA              IS 'Estacoes meteorologicas automaticas do INMET (BDMEP).';
COMMENT ON COLUMN T_ESTACAO_METEOROLOGICA.ID_ESTACAO  IS 'Identificador substituto da estacao (PK).';
COMMENT ON COLUMN T_ESTACAO_METEOROLOGICA.CD_WMO      IS 'Codigo WMO/OMM da estacao (unico). Ex.: A001.';
COMMENT ON COLUMN T_ESTACAO_METEOROLOGICA.NM_ESTACAO  IS 'Nome da estacao meteorologica.';
COMMENT ON COLUMN T_ESTACAO_METEOROLOGICA.ID_ESTADO   IS 'FK para T_ESTADO: UF da estacao.';
COMMENT ON COLUMN T_ESTACAO_METEOROLOGICA.DT_FUNDACAO IS 'Data de fundacao/inicio de operacao da estacao.';

-- 4.2) T_LOCALIZACAO_ESTACAO (relacao 1:1 com a estacao) --------------
CREATE TABLE T_LOCALIZACAO_ESTACAO (
    ID_ESTACAO    NUMBER(6)      NOT NULL,
    LATITUDE      NUMBER(9,6)    NOT NULL,
    LONGITUDE     NUMBER(9,6)    NOT NULL,
    ALTITUDE_M    NUMBER(7,2),
    CONSTRAINT PK_LOC_ESTACAO     PRIMARY KEY (ID_ESTACAO),
    CONSTRAINT FK_LOC_ESTACAO     FOREIGN KEY (ID_ESTACAO)
        REFERENCES T_ESTACAO_METEOROLOGICA (ID_ESTACAO),
    CONSTRAINT CK_LOC_LAT         CHECK (LATITUDE  BETWEEN -90  AND 90),
    CONSTRAINT CK_LOC_LON         CHECK (LONGITUDE BETWEEN -180 AND 180)
);

COMMENT ON TABLE  T_LOCALIZACAO_ESTACAO            IS 'Geolocalizacao da estacao (1:1 com T_ESTACAO_METEOROLOGICA). Decompoe atributos espaciais.';
COMMENT ON COLUMN T_LOCALIZACAO_ESTACAO.ID_ESTACAO IS 'PK e FK 1:1 para T_ESTACAO_METEOROLOGICA.';
COMMENT ON COLUMN T_LOCALIZACAO_ESTACAO.LATITUDE   IS 'Latitude da estacao (graus decimais).';
COMMENT ON COLUMN T_LOCALIZACAO_ESTACAO.LONGITUDE  IS 'Longitude da estacao (graus decimais).';
COMMENT ON COLUMN T_LOCALIZACAO_ESTACAO.ALTITUDE_M IS 'Altitude da estacao (metros).';

-- 4.3) T_MEDICAO_CLIMATICA --------------------------------------------
CREATE TABLE T_MEDICAO_CLIMATICA (
    ID_MEDICAO       NUMBER(12)    NOT NULL,
    ID_ESTACAO       NUMBER(6)     NOT NULL,
    DT_HORA_UTC      TIMESTAMP     NOT NULL,
    PRECIPITACAO_MM  NUMBER(7,2),
    PRESSAO_HPA      NUMBER(7,2),
    PRESSAO_MAX_HPA  NUMBER(7,2),
    PRESSAO_MIN_HPA  NUMBER(7,2),
    RADIACAO_KJ_M2   NUMBER(9,2),
    TEMP_AR_C        NUMBER(5,2),
    TEMP_ORVALHO_C   NUMBER(5,2),
    TEMP_MAX_C       NUMBER(5,2),
    TEMP_MIN_C       NUMBER(5,2),
    UMIDADE_REL_PCT  NUMBER(5,2),
    UMIDADE_MAX_PCT  NUMBER(5,2),
    UMIDADE_MIN_PCT  NUMBER(5,2),
    VENTO_DIR_GRAUS  NUMBER(5,2),
    VENTO_RAJADA_MS  NUMBER(6,2),
    VENTO_VEL_MS     NUMBER(6,2),
    CONSTRAINT PK_MEDICAO           PRIMARY KEY (ID_MEDICAO),
    CONSTRAINT FK_MEDICAO_ESTACAO   FOREIGN KEY (ID_ESTACAO)
        REFERENCES T_ESTACAO_METEOROLOGICA (ID_ESTACAO),
    CONSTRAINT UK_MEDICAO_EST_DT    UNIQUE (ID_ESTACAO, DT_HORA_UTC),
    CONSTRAINT CK_MED_UMID_REL      CHECK (UMIDADE_REL_PCT BETWEEN 0 AND 100),
    CONSTRAINT CK_MED_UMID_MAX      CHECK (UMIDADE_MAX_PCT BETWEEN 0 AND 100),
    CONSTRAINT CK_MED_UMID_MIN      CHECK (UMIDADE_MIN_PCT BETWEEN 0 AND 100),
    CONSTRAINT CK_MED_VENTO_DIR     CHECK (VENTO_DIR_GRAUS BETWEEN 0 AND 360),
    CONSTRAINT CK_MED_PRECIP        CHECK (PRECIPITACAO_MM >= 0),
    CONSTRAINT CK_MED_VENTO_VEL     CHECK (VENTO_VEL_MS >= 0),
    CONSTRAINT CK_MED_VENTO_RAJ     CHECK (VENTO_RAJADA_MS >= 0)
);

COMMENT ON TABLE  T_MEDICAO_CLIMATICA                 IS 'Medicoes horarias das estacoes do INMET (variaveis meteorologicas).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.ID_MEDICAO      IS 'Identificador substituto da medicao (PK).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.ID_ESTACAO      IS 'FK para T_ESTACAO_METEOROLOGICA.';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.DT_HORA_UTC     IS 'Data/hora UTC da medicao horaria.';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.PRECIPITACAO_MM IS 'Precipitacao na hora (mm).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.PRESSAO_HPA     IS 'Pressao atmosferica ao nivel da estacao (hPa).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.RADIACAO_KJ_M2  IS 'Radiacao global (kJ/m2).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.TEMP_AR_C       IS 'Temperatura do ar - bulbo seco (C).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.TEMP_ORVALHO_C  IS 'Temperatura do ponto de orvalho (C).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.UMIDADE_REL_PCT IS 'Umidade relativa do ar (%). Variavel-chave para risco de fogo.';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.VENTO_DIR_GRAUS IS 'Direcao do vento (graus, 0..360).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.VENTO_RAJADA_MS IS 'Rajada maxima de vento (m/s).';
COMMENT ON COLUMN T_MEDICAO_CLIMATICA.VENTO_VEL_MS    IS 'Velocidade media do vento (m/s).';

-- ---------------------------------------------------------------------
-- 5) RELACIONAMENTO N:N FOCO x MEDICAO (associativa)
-- ---------------------------------------------------------------------

-- 5.1) T_FOCO_CONDICAO_CLIM -------------------------------------------
CREATE TABLE T_FOCO_CONDICAO_CLIM (
    ID_FOCO        NUMBER(12)   NOT NULL,
    ID_MEDICAO     NUMBER(12)   NOT NULL,
    DISTANCIA_KM   NUMBER(8,3),
    DIF_TEMPO_MIN  NUMBER(8),
    CONSTRAINT PK_FOCO_COND      PRIMARY KEY (ID_FOCO, ID_MEDICAO),
    CONSTRAINT FK_COND_FOCO      FOREIGN KEY (ID_FOCO)
        REFERENCES T_FOCO_CALOR (ID_FOCO),
    CONSTRAINT FK_COND_MEDICAO   FOREIGN KEY (ID_MEDICAO)
        REFERENCES T_MEDICAO_CLIMATICA (ID_MEDICAO),
    CONSTRAINT CK_COND_DIST      CHECK (DISTANCIA_KM >= 0)
);

COMMENT ON TABLE  T_FOCO_CONDICAO_CLIM               IS 'Associativa N:N entre foco de calor e medicao climatica mais proxima (espaco-tempo).';
COMMENT ON COLUMN T_FOCO_CONDICAO_CLIM.ID_FOCO       IS 'FK para T_FOCO_CALOR (parte da PK composta).';
COMMENT ON COLUMN T_FOCO_CONDICAO_CLIM.ID_MEDICAO    IS 'FK para T_MEDICAO_CLIMATICA (parte da PK composta).';
COMMENT ON COLUMN T_FOCO_CONDICAO_CLIM.DISTANCIA_KM  IS 'Distancia (km) entre o foco e a estacao da medicao associada.';
COMMENT ON COLUMN T_FOCO_CONDICAO_CLIM.DIF_TEMPO_MIN IS 'Diferenca de tempo (minutos) entre a passagem do foco e a medicao.';

-- ---------------------------------------------------------------------
-- 6) DESMATAMENTO POR BIOMA (PRODES)
-- ---------------------------------------------------------------------

-- 6.1) T_DESMATAMENTO_BIOMA -------------------------------------------
CREATE TABLE T_DESMATAMENTO_BIOMA (
    ID_DESMAT          NUMBER(8)     NOT NULL,
    ID_BIOMA           NUMBER(4)     NOT NULL,
    ANO_PRODES         NUMBER(4)     NOT NULL,
    AREA_SUPRIMIDA_KM2 NUMBER(12,2)  NOT NULL,
    VARIACAO_PCT       NUMBER(6,2),
    FONTE              VARCHAR2(60),
    CONSTRAINT PK_DESMAT           PRIMARY KEY (ID_DESMAT),
    CONSTRAINT FK_DESMAT_BIOMA     FOREIGN KEY (ID_BIOMA)
        REFERENCES T_BIOMA (ID_BIOMA),
    CONSTRAINT UK_DESMAT_BIOMA_ANO UNIQUE (ID_BIOMA, ANO_PRODES),
    CONSTRAINT CK_DESMAT_AREA      CHECK (AREA_SUPRIMIDA_KM2 >= 0),
    CONSTRAINT CK_DESMAT_ANO       CHECK (ANO_PRODES BETWEEN 1988 AND 2100)
);

COMMENT ON TABLE  T_DESMATAMENTO_BIOMA                    IS 'Area de desmatamento (supressao vegetal) por bioma e ano, sistema PRODES/INPE.';
COMMENT ON COLUMN T_DESMATAMENTO_BIOMA.ID_DESMAT          IS 'Identificador substituto do registro de desmatamento (PK).';
COMMENT ON COLUMN T_DESMATAMENTO_BIOMA.ID_BIOMA          IS 'FK para T_BIOMA.';
COMMENT ON COLUMN T_DESMATAMENTO_BIOMA.ANO_PRODES         IS 'Ano de referencia do PRODES.';
COMMENT ON COLUMN T_DESMATAMENTO_BIOMA.AREA_SUPRIMIDA_KM2 IS 'Area suprimida no ano (km2).';
COMMENT ON COLUMN T_DESMATAMENTO_BIOMA.VARIACAO_PCT       IS 'Variacao percentual frente ao ano anterior (%).';
COMMENT ON COLUMN T_DESMATAMENTO_BIOMA.FONTE              IS 'Fonte do dado. Ex.: INPE/PRODES-BiomasBR.';

-- ---------------------------------------------------------------------
-- 7) INDICES SECUNDARIOS (performance de consultas analiticas)
--    Indices de PK/UNIQUE sao criados automaticamente pelo Oracle.
-- ---------------------------------------------------------------------
CREATE INDEX IX_FOCO_DT_PASSAGEM ON T_FOCO_CALOR (DT_PASSAGEM);
CREATE INDEX IX_FOCO_BIOMA       ON T_FOCO_CALOR (ID_BIOMA);
CREATE INDEX IX_FOCO_MUNICIPIO   ON T_FOCO_CALOR (ID_MUNICIPIO);
CREATE INDEX IX_FOCO_SATELITE    ON T_FOCO_CALOR (ID_SATELITE);
CREATE INDEX IX_FOCO_RISCO       ON T_FOCO_CALOR (RISCO_FOGO);
CREATE INDEX IX_MUNICIPIO_ESTADO ON T_MUNICIPIO (ID_ESTADO);
CREATE INDEX IX_MEDICAO_ESTACAO  ON T_MEDICAO_CLIMATICA (ID_ESTACAO);
CREATE INDEX IX_MEDICAO_DT       ON T_MEDICAO_CLIMATICA (DT_HORA_UTC);
CREATE INDEX IX_ESTACAO_ESTADO   ON T_ESTACAO_METEOROLOGICA (ID_ESTADO);
CREATE INDEX IX_DESMAT_BIOMA     ON T_DESMATAMENTO_BIOMA (ID_BIOMA);

-- =====================================================================
-- 8) INSERTS DE EXEMPLO COM DADOS REAIS (amostra ilustrativa)
--    A carga completa em volume e gerada pelo ETL:
--    sql/insercoes_dados_reais.sql
-- =====================================================================

-- 8.1) BIOMAS (6 biomas brasileiros) ---------------------------------
INSERT INTO T_BIOMA (ID_BIOMA, NM_BIOMA) VALUES (SEQ_BIOMA.NEXTVAL, 'Amazônia');
INSERT INTO T_BIOMA (ID_BIOMA, NM_BIOMA) VALUES (SEQ_BIOMA.NEXTVAL, 'Cerrado');
INSERT INTO T_BIOMA (ID_BIOMA, NM_BIOMA) VALUES (SEQ_BIOMA.NEXTVAL, 'Caatinga');
INSERT INTO T_BIOMA (ID_BIOMA, NM_BIOMA) VALUES (SEQ_BIOMA.NEXTVAL, 'Mata Atlântica');
INSERT INTO T_BIOMA (ID_BIOMA, NM_BIOMA) VALUES (SEQ_BIOMA.NEXTVAL, 'Pantanal');
INSERT INTO T_BIOMA (ID_BIOMA, NM_BIOMA) VALUES (SEQ_BIOMA.NEXTVAL, 'Pampa');

-- 8.2) ESTADOS (amostra: UFs lider em focos - MATOPIBA + arco) -------
--      ID_ESTADO = codigo IBGE real da UF.
INSERT INTO T_ESTADO (ID_ESTADO, NM_ESTADO, SG_UF, NM_REGIAO) VALUES (21, 'Maranhão',    'MA', 'Nordeste');
INSERT INTO T_ESTADO (ID_ESTADO, NM_ESTADO, SG_UF, NM_REGIAO) VALUES (17, 'Tocantins',   'TO', 'Norte');
INSERT INTO T_ESTADO (ID_ESTADO, NM_ESTADO, SG_UF, NM_REGIAO) VALUES (51, 'Mato Grosso', 'MT', 'Centro-Oeste');
INSERT INTO T_ESTADO (ID_ESTADO, NM_ESTADO, SG_UF, NM_REGIAO) VALUES (22, 'Piauí',       'PI', 'Nordeste');
INSERT INTO T_ESTADO (ID_ESTADO, NM_ESTADO, SG_UF, NM_REGIAO) VALUES (15, 'Pará',        'PA', 'Norte');
INSERT INTO T_ESTADO (ID_ESTADO, NM_ESTADO, SG_UF, NM_REGIAO) VALUES (29, 'Bahia',       'BA', 'Nordeste');

-- 8.3) MUNICIPIOS (amostra: maiores concentracoes de focos) ----------
INSERT INTO T_MUNICIPIO (ID_MUNICIPIO, NM_MUNICIPIO, ID_ESTADO, CD_MICRORREGIAO, LATITUDE, LONGITUDE)
    VALUES (5103254, 'Colniza', 51, 510170, -9.160572, -60.207402);
INSERT INTO T_MUNICIPIO (ID_MUNICIPIO, NM_MUNICIPIO, ID_ESTADO, CD_MICRORREGIAO, LATITUDE, LONGITUDE)
    VALUES (2106706, 'Mirador', 21, 210060, -6.426128, -44.876085);
INSERT INTO T_MUNICIPIO (ID_MUNICIPIO, NM_MUNICIPIO, ID_ESTADO, CD_MICRORREGIAO, LATITUDE, LONGITUDE)
    VALUES (1721000, 'Mateiros', 17, 170015, -10.546389, -46.416389);

-- 8.4) SATELITES (13 satelites; AQUA_M-T = referencia do INPE) -------
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'AQUA_M-T',  'S');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'AQUA_M-M',  'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'TERRA_M-T', 'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'TERRA_M-M', 'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'NOAA-20',   'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'NOAA-21',   'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'NPP-375',   'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'NPP-375D',  'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'GOES-16',   'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'GOES-19',   'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'METOP-B',   'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'METOP-C',   'N');
INSERT INTO T_SATELITE (ID_SATELITE, NM_SATELITE, FL_REFERENCIA) VALUES (SEQ_SATELITE.NEXTVAL, 'MSG-03',    'N');

-- 8.5) FOCOS DE CALOR (amostra real, estacao seca / pico set-out) ----
--      ID_SATELITE/ID_MUNICIPIO/ID_BIOMA usam os ids inseridos acima.
--      Bioma: 1=Amazonia 2=Cerrado 3=Caatinga 4=Mata Atlantica 5=Pantanal 6=Pampa
--      Satelite: 1=AQUA_M-T ... (vide ordem de insercao em 8.4)
INSERT INTO T_FOCO_CALOR (ID_FOCO, FOCO_ID_BDQ, ID_SATELITE, ID_MUNICIPIO, ID_BIOMA,
        DT_PASSAGEM, LATITUDE, LONGITUDE, NUM_DIAS_SEM_CHUVA, PRECIPITACAO_MM, RISCO_FOGO, FRP_MW)
    VALUES (SEQ_FOCO.NEXTVAL, 'BDQ-2025-0001', 1, 5103254, 1,
        TO_TIMESTAMP('2025-09-12 17:30:00','YYYY-MM-DD HH24:MI:SS'),
        -9.160572, -60.207402, 12, 0.0, 0.910, 78.40);
INSERT INTO T_FOCO_CALOR (ID_FOCO, FOCO_ID_BDQ, ID_SATELITE, ID_MUNICIPIO, ID_BIOMA,
        DT_PASSAGEM, LATITUDE, LONGITUDE, NUM_DIAS_SEM_CHUVA, PRECIPITACAO_MM, RISCO_FOGO, FRP_MW)
    VALUES (SEQ_FOCO.NEXTVAL, 'BDQ-2025-0002', 5, 2106706, 2,
        TO_TIMESTAMP('2025-09-20 16:05:00','YYYY-MM-DD HH24:MI:SS'),
        -6.426128, -44.876085, 17, 0.0, 0.968, 39.62);
INSERT INTO T_FOCO_CALOR (ID_FOCO, FOCO_ID_BDQ, ID_SATELITE, ID_MUNICIPIO, ID_BIOMA,
        DT_PASSAGEM, LATITUDE, LONGITUDE, NUM_DIAS_SEM_CHUVA, PRECIPITACAO_MM, RISCO_FOGO, FRP_MW)
    VALUES (SEQ_FOCO.NEXTVAL, 'BDQ-2025-0003', 6, 1721000, 2,
        TO_TIMESTAMP('2025-10-03 16:40:00','YYYY-MM-DD HH24:MI:SS'),
        -10.546389, -46.416389, 22, 0.0, 0.995, 55.10);

-- 8.6) ESTACOES METEOROLOGICAS (amostra INMET) -----------------------
-- (ID_ESTADO 53 = Distrito Federal; inserido ANTES das estacoes para respeitar a FK)
INSERT INTO T_ESTADO (ID_ESTADO, NM_ESTADO, SG_UF, NM_REGIAO) VALUES (53, 'Distrito Federal', 'DF', 'Centro-Oeste');
INSERT INTO T_ESTACAO_METEOROLOGICA (ID_ESTACAO, CD_WMO, NM_ESTACAO, ID_ESTADO, DT_FUNDACAO)
    VALUES (SEQ_ESTACAO.NEXTVAL, 'A001', 'BRASILIA', 53, TO_DATE('2000-05-07','YYYY-MM-DD'));
INSERT INTO T_ESTACAO_METEOROLOGICA (ID_ESTACAO, CD_WMO, NM_ESTACAO, ID_ESTADO, DT_FUNDACAO)
    VALUES (SEQ_ESTACAO.NEXTVAL, 'A042', 'BRAZLANDIA', 53, TO_DATE('2017-07-19','YYYY-MM-DD'));

-- 8.7) LOCALIZACAO DAS ESTACOES (1:1) --------------------------------
INSERT INTO T_LOCALIZACAO_ESTACAO (ID_ESTACAO, LATITUDE, LONGITUDE, ALTITUDE_M)
    VALUES (1, -15.789444, -47.925833, 1160.96);
INSERT INTO T_LOCALIZACAO_ESTACAO (ID_ESTACAO, LATITUDE, LONGITUDE, ALTITUDE_M)
    VALUES (2, -15.599722, -48.131111, 1143.00);

-- 8.8) MEDICOES CLIMATICAS (amostra horaria real, jan/2025) ----------
INSERT INTO T_MEDICAO_CLIMATICA (ID_MEDICAO, ID_ESTACAO, DT_HORA_UTC, PRECIPITACAO_MM,
        PRESSAO_HPA, PRESSAO_MAX_HPA, PRESSAO_MIN_HPA, RADIACAO_KJ_M2, TEMP_AR_C, TEMP_ORVALHO_C,
        TEMP_MAX_C, TEMP_MIN_C, UMIDADE_REL_PCT, UMIDADE_MAX_PCT, UMIDADE_MIN_PCT,
        VENTO_DIR_GRAUS, VENTO_RAJADA_MS, VENTO_VEL_MS)
    VALUES (SEQ_MEDICAO.NEXTVAL, 1, TO_TIMESTAMP('2025-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        0.00, 886.10, 886.10, 885.50, NULL, 20.80, 19.50, 20.90, 20.70, 92, 92, 90, 8, 3.60, 1.80);
INSERT INTO T_MEDICAO_CLIMATICA (ID_MEDICAO, ID_ESTACAO, DT_HORA_UTC, PRECIPITACAO_MM,
        PRESSAO_HPA, PRESSAO_MAX_HPA, PRESSAO_MIN_HPA, RADIACAO_KJ_M2, TEMP_AR_C, TEMP_ORVALHO_C,
        TEMP_MAX_C, TEMP_MIN_C, UMIDADE_REL_PCT, UMIDADE_MAX_PCT, UMIDADE_MIN_PCT,
        VENTO_DIR_GRAUS, VENTO_RAJADA_MS, VENTO_VEL_MS)
    VALUES (SEQ_MEDICAO.NEXTVAL, 1, TO_TIMESTAMP('2025-01-01 01:00:00','YYYY-MM-DD HH24:MI:SS'),
        0.00, 886.30, 886.40, 886.00, NULL, 20.70, 19.30, 20.80, 20.50, 92, 93, 92, 4, 3.40, 1.90);

-- 8.9) FOCO x MEDICAO (associativa N:N) ------------------------------
INSERT INTO T_FOCO_CONDICAO_CLIM (ID_FOCO, ID_MEDICAO, DISTANCIA_KM, DIF_TEMPO_MIN)
    VALUES (1, 1, 842.350, 45);

-- 8.10) DESMATAMENTO POR BIOMA (PRODES 2025 - dados reais) -----------
INSERT INTO T_DESMATAMENTO_BIOMA (ID_DESMAT, ID_BIOMA, ANO_PRODES, AREA_SUPRIMIDA_KM2, VARIACAO_PCT, FONTE)
    VALUES (SEQ_DESMAT.NEXTVAL, 1, 2025, 5796.00,  -11.08, 'INPE/PRODES-BiomasBR');
INSERT INTO T_DESMATAMENTO_BIOMA (ID_DESMAT, ID_BIOMA, ANO_PRODES, AREA_SUPRIMIDA_KM2, VARIACAO_PCT, FONTE)
    VALUES (SEQ_DESMAT.NEXTVAL, 2, 2025, 7235.27,  -11.49, 'INPE/PRODES-BiomasBR');
INSERT INTO T_DESMATAMENTO_BIOMA (ID_DESMAT, ID_BIOMA, ANO_PRODES, AREA_SUPRIMIDA_KM2, VARIACAO_PCT, FONTE)
    VALUES (SEQ_DESMAT.NEXTVAL, 3, 2025, 1501.00,   -3.40, 'INPE/PRODES-BiomasBR');
INSERT INTO T_DESMATAMENTO_BIOMA (ID_DESMAT, ID_BIOMA, ANO_PRODES, AREA_SUPRIMIDA_KM2, VARIACAO_PCT, FONTE)
    VALUES (SEQ_DESMAT.NEXTVAL, 4, 2025,   74.86,   -9.20, 'INPE/PRODES-BiomasBR');
INSERT INTO T_DESMATAMENTO_BIOMA (ID_DESMAT, ID_BIOMA, ANO_PRODES, AREA_SUPRIMIDA_KM2, VARIACAO_PCT, FONTE)
    VALUES (SEQ_DESMAT.NEXTVAL, 5, 2025,  291.21,  -77.00, 'INPE/PRODES-BiomasBR');
INSERT INTO T_DESMATAMENTO_BIOMA (ID_DESMAT, ID_BIOMA, ANO_PRODES, AREA_SUPRIMIDA_KM2, VARIACAO_PCT, FONTE)
    VALUES (SEQ_DESMAT.NEXTVAL, 6, 2025,   92.00,   -5.10, 'INPE/PRODES-BiomasBR');

COMMIT;

-- =====================================================================
-- 9) CONSULTAS ANALITICAS DE VERIFICACAO (exemplos)
-- =====================================================================

-- 9.1) Total de focos por bioma (estacao seca explica o ranking)
-- SELECT b.NM_BIOMA, COUNT(*) AS TOTAL_FOCOS
--   FROM T_FOCO_CALOR f JOIN T_BIOMA b ON b.ID_BIOMA = f.ID_BIOMA
--  GROUP BY b.NM_BIOMA ORDER BY TOTAL_FOCOS DESC;

-- 9.2) Risco medio de fogo e FRP medio por UF
-- SELECT e.SG_UF, ROUND(AVG(f.RISCO_FOGO),3) AS RISCO_MEDIO,
--        ROUND(AVG(f.FRP_MW),2) AS FRP_MEDIO, COUNT(*) FOCOS
--   FROM T_FOCO_CALOR f
--   JOIN T_MUNICIPIO m ON m.ID_MUNICIPIO = f.ID_MUNICIPIO
--   JOIN T_ESTADO e    ON e.ID_ESTADO    = m.ID_ESTADO
--  GROUP BY e.SG_UF ORDER BY FOCOS DESC;

-- 9.3) Desmatamento x focos por bioma (correlacao pressao antropica)
-- SELECT b.NM_BIOMA, d.AREA_SUPRIMIDA_KM2, COUNT(f.ID_FOCO) AS FOCOS
--   FROM T_BIOMA b
--   LEFT JOIN T_DESMATAMENTO_BIOMA d ON d.ID_BIOMA = b.ID_BIOMA AND d.ANO_PRODES = 2025
--   LEFT JOIN T_FOCO_CALOR f         ON f.ID_BIOMA = b.ID_BIOMA
--  GROUP BY b.NM_BIOMA, d.AREA_SUPRIMIDA_KM2 ORDER BY d.AREA_SUPRIMIDA_KM2 DESC;
